/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { messagesGet } from "../funcs/messagesGet.js";
import { messagesList } from "../funcs/messagesList.js";
import { messagesUpdate } from "../funcs/messagesUpdate.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as components from "../models/components/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Messages extends ClientSDK {
  async get(
    request: operations.GetMessageRequest,
    options?: RequestOptions,
  ): Promise<components.MessageResponse> {
    return unwrapAsync(messagesGet(
      this,
      request,
      options,
    ));
  }

  async update(
    request: operations.UpdateMessageRequest,
    options?: RequestOptions,
  ): Promise<components.MessageResponse> {
    return unwrapAsync(messagesUpdate(
      this,
      request,
      options,
    ));
  }

  async list(
    request: operations.ListMessagesRequest,
    options?: RequestOptions,
  ): Promise<Array<components.MessageResponse>> {
    return unwrapAsync(messagesList(
      this,
      request,
      options,
    ));
  }
}
