/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { threadsCreate } from "../funcs/threadsCreate.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as components from "../models/components/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Threads extends ClientSDK {
    async create(
        request: operations.CreateThreadRequest,
        options?: RequestOptions
    ): Promise<components.CreatedThreadResponse> {
        return unwrapAsync(threadsCreate(this, request, options));
    }
}
