/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { remap as remap$ } from "../../lib/primitives.js";
import * as components from "../components/index.js";
import * as z from "zod";

export type ListChannelInvitesRequest = {
    channelId: string;
};

export type ResponseBody =
    | components.GroupDMInviteResponse
    | components.FriendInviteResponse
    | components.GuildInviteResponse;

/** @internal */
export const ListChannelInvitesRequest$inboundSchema: z.ZodType<
    ListChannelInvitesRequest,
    z.ZodTypeDef,
    unknown
> = z
    .object({
        channel_id: z.string(),
    })
    .transform((v) => {
        return remap$(v, {
            channel_id: "channelId",
        });
    });

/** @internal */
export type ListChannelInvitesRequest$Outbound = {
    channel_id: string;
};

/** @internal */
export const ListChannelInvitesRequest$outboundSchema: z.ZodType<
    ListChannelInvitesRequest$Outbound,
    z.ZodTypeDef,
    ListChannelInvitesRequest
> = z
    .object({
        channelId: z.string(),
    })
    .transform((v) => {
        return remap$(v, {
            channelId: "channel_id",
        });
    });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ListChannelInvitesRequest$ {
    /** @deprecated use `ListChannelInvitesRequest$inboundSchema` instead. */
    export const inboundSchema = ListChannelInvitesRequest$inboundSchema;
    /** @deprecated use `ListChannelInvitesRequest$outboundSchema` instead. */
    export const outboundSchema = ListChannelInvitesRequest$outboundSchema;
    /** @deprecated use `ListChannelInvitesRequest$Outbound` instead. */
    export type Outbound = ListChannelInvitesRequest$Outbound;
}

/** @internal */
export const ResponseBody$inboundSchema: z.ZodType<ResponseBody, z.ZodTypeDef, unknown> = z.union([
    components.GroupDMInviteResponse$inboundSchema,
    components.FriendInviteResponse$inboundSchema,
    components.GuildInviteResponse$inboundSchema,
]);

/** @internal */
export type ResponseBody$Outbound =
    | components.GroupDMInviteResponse$Outbound
    | components.FriendInviteResponse$Outbound
    | components.GuildInviteResponse$Outbound;

/** @internal */
export const ResponseBody$outboundSchema: z.ZodType<
    ResponseBody$Outbound,
    z.ZodTypeDef,
    ResponseBody
> = z.union([
    components.GroupDMInviteResponse$outboundSchema,
    components.FriendInviteResponse$outboundSchema,
    components.GuildInviteResponse$outboundSchema,
]);

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ResponseBody$ {
    /** @deprecated use `ResponseBody$inboundSchema` instead. */
    export const inboundSchema = ResponseBody$inboundSchema;
    /** @deprecated use `ResponseBody$outboundSchema` instead. */
    export const outboundSchema = ResponseBody$outboundSchema;
    /** @deprecated use `ResponseBody$Outbound` instead. */
    export type Outbound = ResponseBody$Outbound;
}
