/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type UpdateChannelRequestBody =
  | components.PrivateChannelRequestPartial
  | components.UpdateThreadRequestPartial
  | components.UpdateGuildChannelRequestPartial;

export type UpdateChannelRequest = {
  channelId: string;
  requestBody:
    | components.PrivateChannelRequestPartial
    | components.UpdateThreadRequestPartial
    | components.UpdateGuildChannelRequestPartial;
};

/**
 * 200 response for update_channel
 */
export type UpdateChannelResponseBody =
  | components.PrivateChannelResponse
  | components.PrivateGroupChannelResponse
  | components.ThreadResponse
  | components.GuildChannelResponse;

/** @internal */
export const UpdateChannelRequestBody$inboundSchema: z.ZodType<
  UpdateChannelRequestBody,
  z.ZodTypeDef,
  unknown
> = z.union([
  components.PrivateChannelRequestPartial$inboundSchema,
  components.UpdateThreadRequestPartial$inboundSchema,
  components.UpdateGuildChannelRequestPartial$inboundSchema,
]);

/** @internal */
export type UpdateChannelRequestBody$Outbound =
  | components.PrivateChannelRequestPartial$Outbound
  | components.UpdateThreadRequestPartial$Outbound
  | components.UpdateGuildChannelRequestPartial$Outbound;

/** @internal */
export const UpdateChannelRequestBody$outboundSchema: z.ZodType<
  UpdateChannelRequestBody$Outbound,
  z.ZodTypeDef,
  UpdateChannelRequestBody
> = z.union([
  components.PrivateChannelRequestPartial$outboundSchema,
  components.UpdateThreadRequestPartial$outboundSchema,
  components.UpdateGuildChannelRequestPartial$outboundSchema,
]);

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace UpdateChannelRequestBody$ {
  /** @deprecated use `UpdateChannelRequestBody$inboundSchema` instead. */
  export const inboundSchema = UpdateChannelRequestBody$inboundSchema;
  /** @deprecated use `UpdateChannelRequestBody$outboundSchema` instead. */
  export const outboundSchema = UpdateChannelRequestBody$outboundSchema;
  /** @deprecated use `UpdateChannelRequestBody$Outbound` instead. */
  export type Outbound = UpdateChannelRequestBody$Outbound;
}

export function updateChannelRequestBodyToJSON(
  updateChannelRequestBody: UpdateChannelRequestBody,
): string {
  return JSON.stringify(
    UpdateChannelRequestBody$outboundSchema.parse(updateChannelRequestBody),
  );
}

export function updateChannelRequestBodyFromJSON(
  jsonString: string,
): SafeParseResult<UpdateChannelRequestBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => UpdateChannelRequestBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'UpdateChannelRequestBody' from JSON`,
  );
}

/** @internal */
export const UpdateChannelRequest$inboundSchema: z.ZodType<
  UpdateChannelRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  channel_id: z.string(),
  RequestBody: z.union([
    components.PrivateChannelRequestPartial$inboundSchema,
    components.UpdateThreadRequestPartial$inboundSchema,
    components.UpdateGuildChannelRequestPartial$inboundSchema,
  ]),
}).transform((v) => {
  return remap$(v, {
    "channel_id": "channelId",
    "RequestBody": "requestBody",
  });
});

/** @internal */
export type UpdateChannelRequest$Outbound = {
  channel_id: string;
  RequestBody:
    | components.PrivateChannelRequestPartial$Outbound
    | components.UpdateThreadRequestPartial$Outbound
    | components.UpdateGuildChannelRequestPartial$Outbound;
};

/** @internal */
export const UpdateChannelRequest$outboundSchema: z.ZodType<
  UpdateChannelRequest$Outbound,
  z.ZodTypeDef,
  UpdateChannelRequest
> = z.object({
  channelId: z.string(),
  requestBody: z.union([
    components.PrivateChannelRequestPartial$outboundSchema,
    components.UpdateThreadRequestPartial$outboundSchema,
    components.UpdateGuildChannelRequestPartial$outboundSchema,
  ]),
}).transform((v) => {
  return remap$(v, {
    channelId: "channel_id",
    requestBody: "RequestBody",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace UpdateChannelRequest$ {
  /** @deprecated use `UpdateChannelRequest$inboundSchema` instead. */
  export const inboundSchema = UpdateChannelRequest$inboundSchema;
  /** @deprecated use `UpdateChannelRequest$outboundSchema` instead. */
  export const outboundSchema = UpdateChannelRequest$outboundSchema;
  /** @deprecated use `UpdateChannelRequest$Outbound` instead. */
  export type Outbound = UpdateChannelRequest$Outbound;
}

export function updateChannelRequestToJSON(
  updateChannelRequest: UpdateChannelRequest,
): string {
  return JSON.stringify(
    UpdateChannelRequest$outboundSchema.parse(updateChannelRequest),
  );
}

export function updateChannelRequestFromJSON(
  jsonString: string,
): SafeParseResult<UpdateChannelRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => UpdateChannelRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'UpdateChannelRequest' from JSON`,
  );
}

/** @internal */
export const UpdateChannelResponseBody$inboundSchema: z.ZodType<
  UpdateChannelResponseBody,
  z.ZodTypeDef,
  unknown
> = z.union([
  components.PrivateChannelResponse$inboundSchema,
  components.PrivateGroupChannelResponse$inboundSchema,
  components.ThreadResponse$inboundSchema,
  components.GuildChannelResponse$inboundSchema,
]);

/** @internal */
export type UpdateChannelResponseBody$Outbound =
  | components.PrivateChannelResponse$Outbound
  | components.PrivateGroupChannelResponse$Outbound
  | components.ThreadResponse$Outbound
  | components.GuildChannelResponse$Outbound;

/** @internal */
export const UpdateChannelResponseBody$outboundSchema: z.ZodType<
  UpdateChannelResponseBody$Outbound,
  z.ZodTypeDef,
  UpdateChannelResponseBody
> = z.union([
  components.PrivateChannelResponse$outboundSchema,
  components.PrivateGroupChannelResponse$outboundSchema,
  components.ThreadResponse$outboundSchema,
  components.GuildChannelResponse$outboundSchema,
]);

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace UpdateChannelResponseBody$ {
  /** @deprecated use `UpdateChannelResponseBody$inboundSchema` instead. */
  export const inboundSchema = UpdateChannelResponseBody$inboundSchema;
  /** @deprecated use `UpdateChannelResponseBody$outboundSchema` instead. */
  export const outboundSchema = UpdateChannelResponseBody$outboundSchema;
  /** @deprecated use `UpdateChannelResponseBody$Outbound` instead. */
  export type Outbound = UpdateChannelResponseBody$Outbound;
}

export function updateChannelResponseBodyToJSON(
  updateChannelResponseBody: UpdateChannelResponseBody,
): string {
  return JSON.stringify(
    UpdateChannelResponseBody$outboundSchema.parse(updateChannelResponseBody),
  );
}

export function updateChannelResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<UpdateChannelResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => UpdateChannelResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'UpdateChannelResponseBody' from JSON`,
  );
}
