/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { remap as remap$ } from "../../lib/primitives.js";
import * as components from "../components/index.js";
import * as z from "zod";

export type UpdateMessageRequest = {
    channelId: string;
    messageId: string;
    messageEditRequestPartial: components.MessageEditRequestPartial;
};

/** @internal */
export const UpdateMessageRequest$inboundSchema: z.ZodType<
    UpdateMessageRequest,
    z.ZodTypeDef,
    unknown
> = z
    .object({
        channel_id: z.string(),
        message_id: z.string(),
        MessageEditRequestPartial: components.MessageEditRequestPartial$inboundSchema,
    })
    .transform((v) => {
        return remap$(v, {
            channel_id: "channelId",
            message_id: "messageId",
            MessageEditRequestPartial: "messageEditRequestPartial",
        });
    });

/** @internal */
export type UpdateMessageRequest$Outbound = {
    channel_id: string;
    message_id: string;
    MessageEditRequestPartial: components.MessageEditRequestPartial$Outbound;
};

/** @internal */
export const UpdateMessageRequest$outboundSchema: z.ZodType<
    UpdateMessageRequest$Outbound,
    z.ZodTypeDef,
    UpdateMessageRequest
> = z
    .object({
        channelId: z.string(),
        messageId: z.string(),
        messageEditRequestPartial: components.MessageEditRequestPartial$outboundSchema,
    })
    .transform((v) => {
        return remap$(v, {
            channelId: "channel_id",
            messageId: "message_id",
            messageEditRequestPartial: "MessageEditRequestPartial",
        });
    });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace UpdateMessageRequest$ {
    /** @deprecated use `UpdateMessageRequest$inboundSchema` instead. */
    export const inboundSchema = UpdateMessageRequest$inboundSchema;
    /** @deprecated use `UpdateMessageRequest$outboundSchema` instead. */
    export const outboundSchema = UpdateMessageRequest$outboundSchema;
    /** @deprecated use `UpdateMessageRequest$Outbound` instead. */
    export type Outbound = UpdateMessageRequest$Outbound;
}
