/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type ApplicationOAuth2InstallParamsResponse = {
  scopes: Array<string>;
  permissions: string;
};

/** @internal */
export const ApplicationOAuth2InstallParamsResponse$inboundSchema: z.ZodType<
  ApplicationOAuth2InstallParamsResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  scopes: z.array(z.string()),
  permissions: z.string(),
});

/** @internal */
export type ApplicationOAuth2InstallParamsResponse$Outbound = {
  scopes: Array<string>;
  permissions: string;
};

/** @internal */
export const ApplicationOAuth2InstallParamsResponse$outboundSchema: z.ZodType<
  ApplicationOAuth2InstallParamsResponse$Outbound,
  z.ZodTypeDef,
  ApplicationOAuth2InstallParamsResponse
> = z.object({
  scopes: z.array(z.string()),
  permissions: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ApplicationOAuth2InstallParamsResponse$ {
  /** @deprecated use `ApplicationOAuth2InstallParamsResponse$inboundSchema` instead. */
  export const inboundSchema =
    ApplicationOAuth2InstallParamsResponse$inboundSchema;
  /** @deprecated use `ApplicationOAuth2InstallParamsResponse$outboundSchema` instead. */
  export const outboundSchema =
    ApplicationOAuth2InstallParamsResponse$outboundSchema;
  /** @deprecated use `ApplicationOAuth2InstallParamsResponse$Outbound` instead. */
  export type Outbound = ApplicationOAuth2InstallParamsResponse$Outbound;
}

export function applicationOAuth2InstallParamsResponseToJSON(
  applicationOAuth2InstallParamsResponse:
    ApplicationOAuth2InstallParamsResponse,
): string {
  return JSON.stringify(
    ApplicationOAuth2InstallParamsResponse$outboundSchema.parse(
      applicationOAuth2InstallParamsResponse,
    ),
  );
}

export function applicationOAuth2InstallParamsResponseFromJSON(
  jsonString: string,
): SafeParseResult<ApplicationOAuth2InstallParamsResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      ApplicationOAuth2InstallParamsResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ApplicationOAuth2InstallParamsResponse' from JSON`,
  );
}
