/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type ApplicationIntegrationTypeConfigurationResponse = {};

/** @internal */
export const ApplicationIntegrationTypeConfigurationResponse$inboundSchema: z.ZodType<
    ApplicationIntegrationTypeConfigurationResponse,
    z.ZodTypeDef,
    unknown
> = z.object({});

/** @internal */
export type ApplicationIntegrationTypeConfigurationResponse$Outbound = {};

/** @internal */
export const ApplicationIntegrationTypeConfigurationResponse$outboundSchema: z.ZodType<
    ApplicationIntegrationTypeConfigurationResponse$Outbound,
    z.ZodTypeDef,
    ApplicationIntegrationTypeConfigurationResponse
> = z.object({});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ApplicationIntegrationTypeConfigurationResponse$ {
    /** @deprecated use `ApplicationIntegrationTypeConfigurationResponse$inboundSchema` instead. */
    export const inboundSchema = ApplicationIntegrationTypeConfigurationResponse$inboundSchema;
    /** @deprecated use `ApplicationIntegrationTypeConfigurationResponse$outboundSchema` instead. */
    export const outboundSchema = ApplicationIntegrationTypeConfigurationResponse$outboundSchema;
    /** @deprecated use `ApplicationIntegrationTypeConfigurationResponse$Outbound` instead. */
    export type Outbound = ApplicationIntegrationTypeConfigurationResponse$Outbound;
}
