/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";

export type CreateGroupDMInviteRequest = {
  maxAge?: number | null | undefined;
};

/** @internal */
export const CreateGroupDMInviteRequest$inboundSchema: z.ZodType<
  CreateGroupDMInviteRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  max_age: z.nullable(z.number().int()).optional(),
}).transform((v) => {
  return remap$(v, {
    "max_age": "maxAge",
  });
});

/** @internal */
export type CreateGroupDMInviteRequest$Outbound = {
  max_age?: number | null | undefined;
};

/** @internal */
export const CreateGroupDMInviteRequest$outboundSchema: z.ZodType<
  CreateGroupDMInviteRequest$Outbound,
  z.ZodTypeDef,
  CreateGroupDMInviteRequest
> = z.object({
  maxAge: z.nullable(z.number().int()).optional(),
}).transform((v) => {
  return remap$(v, {
    maxAge: "max_age",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace CreateGroupDMInviteRequest$ {
  /** @deprecated use `CreateGroupDMInviteRequest$inboundSchema` instead. */
  export const inboundSchema = CreateGroupDMInviteRequest$inboundSchema;
  /** @deprecated use `CreateGroupDMInviteRequest$outboundSchema` instead. */
  export const outboundSchema = CreateGroupDMInviteRequest$outboundSchema;
  /** @deprecated use `CreateGroupDMInviteRequest$Outbound` instead. */
  export type Outbound = CreateGroupDMInviteRequest$Outbound;
}
