/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { remap as remap$ } from "../../lib/primitives.js";
import {
    ChannelPermissionOverwriteResponse,
    ChannelPermissionOverwriteResponse$inboundSchema,
    ChannelPermissionOverwriteResponse$Outbound,
    ChannelPermissionOverwriteResponse$outboundSchema,
} from "./channelpermissionoverwriteresponse.js";
import {
    DefaultReactionEmojiResponse,
    DefaultReactionEmojiResponse$inboundSchema,
    DefaultReactionEmojiResponse$Outbound,
    DefaultReactionEmojiResponse$outboundSchema,
} from "./defaultreactionemojiresponse.js";
import {
    ForumTagResponse,
    ForumTagResponse$inboundSchema,
    ForumTagResponse$Outbound,
    ForumTagResponse$outboundSchema,
} from "./forumtagresponse.js";
import * as z from "zod";

export type GuildChannelResponse = {
    id: string;
    type?: 1 | undefined;
    lastMessageId?: string | null | undefined;
    flags: number;
    lastPinTimestamp?: Date | null | undefined;
    guildId: string;
    name: string;
    parentId?: string | null | undefined;
    rateLimitPerUser?: number | null | undefined;
    bitrate?: number | null | undefined;
    userLimit?: number | null | undefined;
    rtcRegion?: string | null | undefined;
    videoQualityMode?: 1 | null | undefined;
    permissions?: string | null | undefined;
    topic?: string | null | undefined;
    defaultAutoArchiveDuration?: 60 | null | undefined;
    defaultThreadRateLimitPerUser?: number | null | undefined;
    position: number;
    permissionOverwrites?: Array<ChannelPermissionOverwriteResponse> | null | undefined;
    nsfw?: boolean | null | undefined;
    availableTags?: Array<ForumTagResponse> | null | undefined;
    defaultReactionEmoji?: DefaultReactionEmojiResponse | null | undefined;
    defaultSortOrder?: 0 | null | undefined;
    defaultForumLayout?: 0 | null | undefined;
};

/** @internal */
export const GuildChannelResponse$inboundSchema: z.ZodType<
    GuildChannelResponse,
    z.ZodTypeDef,
    unknown
> = z
    .object({
        id: z.string(),
        type: z.literal(1).optional(),
        last_message_id: z.nullable(z.string()).optional(),
        flags: z.number().int(),
        last_pin_timestamp: z
            .nullable(
                z
                    .string()
                    .datetime({ offset: true })
                    .transform((v) => new Date(v))
            )
            .optional(),
        guild_id: z.string(),
        name: z.string(),
        parent_id: z.nullable(z.string()).optional(),
        rate_limit_per_user: z.nullable(z.number().int()).optional(),
        bitrate: z.nullable(z.number().int()).optional(),
        user_limit: z.nullable(z.number().int()).optional(),
        rtc_region: z.nullable(z.string()).optional(),
        video_quality_mode: z.nullable(z.literal(1)).optional(),
        permissions: z.nullable(z.string()).optional(),
        topic: z.nullable(z.string()).optional(),
        default_auto_archive_duration: z.nullable(z.literal(60)).optional(),
        default_thread_rate_limit_per_user: z.nullable(z.number().int()).optional(),
        position: z.number().int(),
        permission_overwrites: z
            .nullable(z.array(ChannelPermissionOverwriteResponse$inboundSchema))
            .optional(),
        nsfw: z.nullable(z.boolean()).optional(),
        available_tags: z.nullable(z.array(ForumTagResponse$inboundSchema)).optional(),
        default_reaction_emoji: z.nullable(DefaultReactionEmojiResponse$inboundSchema).optional(),
        default_sort_order: z.nullable(z.literal(0)).optional(),
        default_forum_layout: z.nullable(z.literal(0)).optional(),
    })
    .transform((v) => {
        return remap$(v, {
            last_message_id: "lastMessageId",
            last_pin_timestamp: "lastPinTimestamp",
            guild_id: "guildId",
            parent_id: "parentId",
            rate_limit_per_user: "rateLimitPerUser",
            user_limit: "userLimit",
            rtc_region: "rtcRegion",
            video_quality_mode: "videoQualityMode",
            default_auto_archive_duration: "defaultAutoArchiveDuration",
            default_thread_rate_limit_per_user: "defaultThreadRateLimitPerUser",
            permission_overwrites: "permissionOverwrites",
            available_tags: "availableTags",
            default_reaction_emoji: "defaultReactionEmoji",
            default_sort_order: "defaultSortOrder",
            default_forum_layout: "defaultForumLayout",
        });
    });

/** @internal */
export type GuildChannelResponse$Outbound = {
    id: string;
    type: 1;
    last_message_id?: string | null | undefined;
    flags: number;
    last_pin_timestamp?: string | null | undefined;
    guild_id: string;
    name: string;
    parent_id?: string | null | undefined;
    rate_limit_per_user?: number | null | undefined;
    bitrate?: number | null | undefined;
    user_limit?: number | null | undefined;
    rtc_region?: string | null | undefined;
    video_quality_mode: 1 | null;
    permissions?: string | null | undefined;
    topic?: string | null | undefined;
    default_auto_archive_duration: 60 | null;
    default_thread_rate_limit_per_user?: number | null | undefined;
    position: number;
    permission_overwrites?: Array<ChannelPermissionOverwriteResponse$Outbound> | null | undefined;
    nsfw?: boolean | null | undefined;
    available_tags?: Array<ForumTagResponse$Outbound> | null | undefined;
    default_reaction_emoji?: DefaultReactionEmojiResponse$Outbound | null | undefined;
    default_sort_order: 0 | null;
    default_forum_layout: 0 | null;
};

/** @internal */
export const GuildChannelResponse$outboundSchema: z.ZodType<
    GuildChannelResponse$Outbound,
    z.ZodTypeDef,
    GuildChannelResponse
> = z
    .object({
        id: z.string(),
        type: z.literal(1).default(1 as const),
        lastMessageId: z.nullable(z.string()).optional(),
        flags: z.number().int(),
        lastPinTimestamp: z.nullable(z.date().transform((v) => v.toISOString())).optional(),
        guildId: z.string(),
        name: z.string(),
        parentId: z.nullable(z.string()).optional(),
        rateLimitPerUser: z.nullable(z.number().int()).optional(),
        bitrate: z.nullable(z.number().int()).optional(),
        userLimit: z.nullable(z.number().int()).optional(),
        rtcRegion: z.nullable(z.string()).optional(),
        videoQualityMode: z.nullable(z.literal(1).default(1 as const)),
        permissions: z.nullable(z.string()).optional(),
        topic: z.nullable(z.string()).optional(),
        defaultAutoArchiveDuration: z.nullable(z.literal(60).default(60 as const)),
        defaultThreadRateLimitPerUser: z.nullable(z.number().int()).optional(),
        position: z.number().int(),
        permissionOverwrites: z
            .nullable(z.array(ChannelPermissionOverwriteResponse$outboundSchema))
            .optional(),
        nsfw: z.nullable(z.boolean()).optional(),
        availableTags: z.nullable(z.array(ForumTagResponse$outboundSchema)).optional(),
        defaultReactionEmoji: z.nullable(DefaultReactionEmojiResponse$outboundSchema).optional(),
        defaultSortOrder: z.nullable(z.literal(0).default(0 as const)),
        defaultForumLayout: z.nullable(z.literal(0).default(0 as const)),
    })
    .transform((v) => {
        return remap$(v, {
            lastMessageId: "last_message_id",
            lastPinTimestamp: "last_pin_timestamp",
            guildId: "guild_id",
            parentId: "parent_id",
            rateLimitPerUser: "rate_limit_per_user",
            userLimit: "user_limit",
            rtcRegion: "rtc_region",
            videoQualityMode: "video_quality_mode",
            defaultAutoArchiveDuration: "default_auto_archive_duration",
            defaultThreadRateLimitPerUser: "default_thread_rate_limit_per_user",
            permissionOverwrites: "permission_overwrites",
            availableTags: "available_tags",
            defaultReactionEmoji: "default_reaction_emoji",
            defaultSortOrder: "default_sort_order",
            defaultForumLayout: "default_forum_layout",
        });
    });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GuildChannelResponse$ {
    /** @deprecated use `GuildChannelResponse$inboundSchema` instead. */
    export const inboundSchema = GuildChannelResponse$inboundSchema;
    /** @deprecated use `GuildChannelResponse$outboundSchema` instead. */
    export const outboundSchema = GuildChannelResponse$outboundSchema;
    /** @deprecated use `GuildChannelResponse$Outbound` instead. */
    export type Outbound = GuildChannelResponse$Outbound;
}
