/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";

export type MessageComponentMentionableSelectResponse = {
  type?: 1 | undefined;
  id: number;
  customId: string;
  placeholder?: string | null | undefined;
  minValues?: number | null | undefined;
  maxValues?: number | null | undefined;
  disabled?: boolean | null | undefined;
};

/** @internal */
export const MessageComponentMentionableSelectResponse$inboundSchema: z.ZodType<
  MessageComponentMentionableSelectResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  type: z.literal(1).optional(),
  id: z.number().int(),
  custom_id: z.string(),
  placeholder: z.nullable(z.string()).optional(),
  min_values: z.nullable(z.number().int()).optional(),
  max_values: z.nullable(z.number().int()).optional(),
  disabled: z.nullable(z.boolean()).optional(),
}).transform((v) => {
  return remap$(v, {
    "custom_id": "customId",
    "min_values": "minValues",
    "max_values": "maxValues",
  });
});

/** @internal */
export type MessageComponentMentionableSelectResponse$Outbound = {
  type: 1;
  id: number;
  custom_id: string;
  placeholder?: string | null | undefined;
  min_values?: number | null | undefined;
  max_values?: number | null | undefined;
  disabled?: boolean | null | undefined;
};

/** @internal */
export const MessageComponentMentionableSelectResponse$outboundSchema:
  z.ZodType<
    MessageComponentMentionableSelectResponse$Outbound,
    z.ZodTypeDef,
    MessageComponentMentionableSelectResponse
  > = z.object({
    type: z.literal(1).default(1 as const),
    id: z.number().int(),
    customId: z.string(),
    placeholder: z.nullable(z.string()).optional(),
    minValues: z.nullable(z.number().int()).optional(),
    maxValues: z.nullable(z.number().int()).optional(),
    disabled: z.nullable(z.boolean()).optional(),
  }).transform((v) => {
    return remap$(v, {
      customId: "custom_id",
      minValues: "min_values",
      maxValues: "max_values",
    });
  });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace MessageComponentMentionableSelectResponse$ {
  /** @deprecated use `MessageComponentMentionableSelectResponse$inboundSchema` instead. */
  export const inboundSchema =
    MessageComponentMentionableSelectResponse$inboundSchema;
  /** @deprecated use `MessageComponentMentionableSelectResponse$outboundSchema` instead. */
  export const outboundSchema =
    MessageComponentMentionableSelectResponse$outboundSchema;
  /** @deprecated use `MessageComponentMentionableSelectResponse$Outbound` instead. */
  export type Outbound = MessageComponentMentionableSelectResponse$Outbound;
}
