/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type MessageComponentEmojiResponse = {
  id?: string | null | undefined;
  name: string;
  animated?: boolean | null | undefined;
};

/** @internal */
export const MessageComponentEmojiResponse$inboundSchema: z.ZodType<
  MessageComponentEmojiResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.nullable(z.string()).optional(),
  name: z.string(),
  animated: z.nullable(z.boolean()).optional(),
});

/** @internal */
export type MessageComponentEmojiResponse$Outbound = {
  id?: string | null | undefined;
  name: string;
  animated?: boolean | null | undefined;
};

/** @internal */
export const MessageComponentEmojiResponse$outboundSchema: z.ZodType<
  MessageComponentEmojiResponse$Outbound,
  z.ZodTypeDef,
  MessageComponentEmojiResponse
> = z.object({
  id: z.nullable(z.string()).optional(),
  name: z.string(),
  animated: z.nullable(z.boolean()).optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace MessageComponentEmojiResponse$ {
  /** @deprecated use `MessageComponentEmojiResponse$inboundSchema` instead. */
  export const inboundSchema = MessageComponentEmojiResponse$inboundSchema;
  /** @deprecated use `MessageComponentEmojiResponse$outboundSchema` instead. */
  export const outboundSchema = MessageComponentEmojiResponse$outboundSchema;
  /** @deprecated use `MessageComponentEmojiResponse$Outbound` instead. */
  export type Outbound = MessageComponentEmojiResponse$Outbound;
}
