/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  GuildProductPurchaseResponse,
  GuildProductPurchaseResponse$inboundSchema,
  GuildProductPurchaseResponse$Outbound,
  GuildProductPurchaseResponse$outboundSchema,
} from "./guildproductpurchaseresponse.js";

export type PurchaseNotificationResponse = {
  type?: 0 | undefined;
  guildProductPurchase?: GuildProductPurchaseResponse | null | undefined;
};

/** @internal */
export const PurchaseNotificationResponse$inboundSchema: z.ZodType<
  PurchaseNotificationResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  type: z.literal(0).optional(),
  guild_product_purchase: z.nullable(GuildProductPurchaseResponse$inboundSchema)
    .optional(),
}).transform((v) => {
  return remap$(v, {
    "guild_product_purchase": "guildProductPurchase",
  });
});

/** @internal */
export type PurchaseNotificationResponse$Outbound = {
  type: 0;
  guild_product_purchase?:
    | GuildProductPurchaseResponse$Outbound
    | null
    | undefined;
};

/** @internal */
export const PurchaseNotificationResponse$outboundSchema: z.ZodType<
  PurchaseNotificationResponse$Outbound,
  z.ZodTypeDef,
  PurchaseNotificationResponse
> = z.object({
  type: z.literal(0).default(0 as const),
  guildProductPurchase: z.nullable(GuildProductPurchaseResponse$outboundSchema)
    .optional(),
}).transform((v) => {
  return remap$(v, {
    guildProductPurchase: "guild_product_purchase",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PurchaseNotificationResponse$ {
  /** @deprecated use `PurchaseNotificationResponse$inboundSchema` instead. */
  export const inboundSchema = PurchaseNotificationResponse$inboundSchema;
  /** @deprecated use `PurchaseNotificationResponse$outboundSchema` instead. */
  export const outboundSchema = PurchaseNotificationResponse$outboundSchema;
  /** @deprecated use `PurchaseNotificationResponse$Outbound` instead. */
  export type Outbound = PurchaseNotificationResponse$Outbound;
}

export function purchaseNotificationResponseToJSON(
  purchaseNotificationResponse: PurchaseNotificationResponse,
): string {
  return JSON.stringify(
    PurchaseNotificationResponse$outboundSchema.parse(
      purchaseNotificationResponse,
    ),
  );
}

export function purchaseNotificationResponseFromJSON(
  jsonString: string,
): SafeParseResult<PurchaseNotificationResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PurchaseNotificationResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PurchaseNotificationResponse' from JSON`,
  );
}
