/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type RichEmbedFooter = {
  text?: string | null | undefined;
  iconUrl?: string | null | undefined;
};

/** @internal */
export const RichEmbedFooter$inboundSchema: z.ZodType<
  RichEmbedFooter,
  z.ZodTypeDef,
  unknown
> = z.object({
  text: z.nullable(z.string()).optional(),
  icon_url: z.nullable(z.string()).optional(),
}).transform((v) => {
  return remap$(v, {
    "icon_url": "iconUrl",
  });
});

/** @internal */
export type RichEmbedFooter$Outbound = {
  text?: string | null | undefined;
  icon_url?: string | null | undefined;
};

/** @internal */
export const RichEmbedFooter$outboundSchema: z.ZodType<
  RichEmbedFooter$Outbound,
  z.ZodTypeDef,
  RichEmbedFooter
> = z.object({
  text: z.nullable(z.string()).optional(),
  iconUrl: z.nullable(z.string()).optional(),
}).transform((v) => {
  return remap$(v, {
    iconUrl: "icon_url",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace RichEmbedFooter$ {
  /** @deprecated use `RichEmbedFooter$inboundSchema` instead. */
  export const inboundSchema = RichEmbedFooter$inboundSchema;
  /** @deprecated use `RichEmbedFooter$outboundSchema` instead. */
  export const outboundSchema = RichEmbedFooter$outboundSchema;
  /** @deprecated use `RichEmbedFooter$Outbound` instead. */
  export type Outbound = RichEmbedFooter$Outbound;
}

export function richEmbedFooterToJSON(
  richEmbedFooter: RichEmbedFooter,
): string {
  return JSON.stringify(RichEmbedFooter$outboundSchema.parse(richEmbedFooter));
}

export function richEmbedFooterFromJSON(
  jsonString: string,
): SafeParseResult<RichEmbedFooter, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => RichEmbedFooter$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'RichEmbedFooter' from JSON`,
  );
}
