/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type RichEmbedProvider = {
  name?: string | null | undefined;
  url?: string | null | undefined;
};

/** @internal */
export const RichEmbedProvider$inboundSchema: z.ZodType<
  RichEmbedProvider,
  z.ZodTypeDef,
  unknown
> = z.object({
  name: z.nullable(z.string()).optional(),
  url: z.nullable(z.string()).optional(),
});

/** @internal */
export type RichEmbedProvider$Outbound = {
  name?: string | null | undefined;
  url?: string | null | undefined;
};

/** @internal */
export const RichEmbedProvider$outboundSchema: z.ZodType<
  RichEmbedProvider$Outbound,
  z.ZodTypeDef,
  RichEmbedProvider
> = z.object({
  name: z.nullable(z.string()).optional(),
  url: z.nullable(z.string()).optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace RichEmbedProvider$ {
  /** @deprecated use `RichEmbedProvider$inboundSchema` instead. */
  export const inboundSchema = RichEmbedProvider$inboundSchema;
  /** @deprecated use `RichEmbedProvider$outboundSchema` instead. */
  export const outboundSchema = RichEmbedProvider$outboundSchema;
  /** @deprecated use `RichEmbedProvider$Outbound` instead. */
  export type Outbound = RichEmbedProvider$Outbound;
}

export function richEmbedProviderToJSON(
  richEmbedProvider: RichEmbedProvider,
): string {
  return JSON.stringify(
    RichEmbedProvider$outboundSchema.parse(richEmbedProvider),
  );
}

export function richEmbedProviderFromJSON(
  jsonString: string,
): SafeParseResult<RichEmbedProvider, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => RichEmbedProvider$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'RichEmbedProvider' from JSON`,
  );
}
