/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";

export type RichEmbedVideo = {
  url?: string | null | undefined;
  width?: number | null | undefined;
  height?: number | null | undefined;
  placeholder?: string | null | undefined;
  placeholderVersion?: number | null | undefined;
};

/** @internal */
export const RichEmbedVideo$inboundSchema: z.ZodType<
  RichEmbedVideo,
  z.ZodTypeDef,
  unknown
> = z.object({
  url: z.nullable(z.string()).optional(),
  width: z.nullable(z.number().int()).optional(),
  height: z.nullable(z.number().int()).optional(),
  placeholder: z.nullable(z.string()).optional(),
  placeholder_version: z.nullable(z.number().int()).optional(),
}).transform((v) => {
  return remap$(v, {
    "placeholder_version": "placeholderVersion",
  });
});

/** @internal */
export type RichEmbedVideo$Outbound = {
  url?: string | null | undefined;
  width?: number | null | undefined;
  height?: number | null | undefined;
  placeholder?: string | null | undefined;
  placeholder_version?: number | null | undefined;
};

/** @internal */
export const RichEmbedVideo$outboundSchema: z.ZodType<
  RichEmbedVideo$Outbound,
  z.ZodTypeDef,
  RichEmbedVideo
> = z.object({
  url: z.nullable(z.string()).optional(),
  width: z.nullable(z.number().int()).optional(),
  height: z.nullable(z.number().int()).optional(),
  placeholder: z.nullable(z.string()).optional(),
  placeholderVersion: z.nullable(z.number().int()).optional(),
}).transform((v) => {
  return remap$(v, {
    placeholderVersion: "placeholder_version",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace RichEmbedVideo$ {
  /** @deprecated use `RichEmbedVideo$inboundSchema` instead. */
  export const inboundSchema = RichEmbedVideo$inboundSchema;
  /** @deprecated use `RichEmbedVideo$outboundSchema` instead. */
  export const outboundSchema = RichEmbedVideo$outboundSchema;
  /** @deprecated use `RichEmbedVideo$Outbound` instead. */
  export type Outbound = RichEmbedVideo$Outbound;
}
