/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import {
  GuildMemberResponse,
  GuildMemberResponse$inboundSchema,
  GuildMemberResponse$Outbound,
  GuildMemberResponse$outboundSchema,
} from "./guildmemberresponse.js";
import {
  UserResponse,
  UserResponse$inboundSchema,
  UserResponse$Outbound,
  UserResponse$outboundSchema,
} from "./userresponse.js";

export type ScheduledEventUserResponse = {
  guildScheduledEventId: string;
  guildScheduledEventExceptionId?: string | null | undefined;
  userId: string;
  user?: UserResponse | null | undefined;
  member?: GuildMemberResponse | null | undefined;
  response?: 0 | undefined;
};

/** @internal */
export const ScheduledEventUserResponse$inboundSchema: z.ZodType<
  ScheduledEventUserResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  guild_scheduled_event_id: z.string(),
  guild_scheduled_event_exception_id: z.nullable(z.string()).optional(),
  user_id: z.string(),
  user: z.nullable(UserResponse$inboundSchema).optional(),
  member: z.nullable(GuildMemberResponse$inboundSchema).optional(),
  response: z.literal(0).optional(),
}).transform((v) => {
  return remap$(v, {
    "guild_scheduled_event_id": "guildScheduledEventId",
    "guild_scheduled_event_exception_id": "guildScheduledEventExceptionId",
    "user_id": "userId",
  });
});

/** @internal */
export type ScheduledEventUserResponse$Outbound = {
  guild_scheduled_event_id: string;
  guild_scheduled_event_exception_id?: string | null | undefined;
  user_id: string;
  user?: UserResponse$Outbound | null | undefined;
  member?: GuildMemberResponse$Outbound | null | undefined;
  response: 0;
};

/** @internal */
export const ScheduledEventUserResponse$outboundSchema: z.ZodType<
  ScheduledEventUserResponse$Outbound,
  z.ZodTypeDef,
  ScheduledEventUserResponse
> = z.object({
  guildScheduledEventId: z.string(),
  guildScheduledEventExceptionId: z.nullable(z.string()).optional(),
  userId: z.string(),
  user: z.nullable(UserResponse$outboundSchema).optional(),
  member: z.nullable(GuildMemberResponse$outboundSchema).optional(),
  response: z.literal(0).default(0 as const),
}).transform((v) => {
  return remap$(v, {
    guildScheduledEventId: "guild_scheduled_event_id",
    guildScheduledEventExceptionId: "guild_scheduled_event_exception_id",
    userId: "user_id",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ScheduledEventUserResponse$ {
  /** @deprecated use `ScheduledEventUserResponse$inboundSchema` instead. */
  export const inboundSchema = ScheduledEventUserResponse$inboundSchema;
  /** @deprecated use `ScheduledEventUserResponse$outboundSchema` instead. */
  export const outboundSchema = ScheduledEventUserResponse$outboundSchema;
  /** @deprecated use `ScheduledEventUserResponse$Outbound` instead. */
  export type Outbound = ScheduledEventUserResponse$Outbound;
}
