/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import {
  SelectOption,
  SelectOption$inboundSchema,
  SelectOption$Outbound,
  SelectOption$outboundSchema,
} from "./selectoption.js";

export type StringSelect = {
  type?: 1 | undefined;
  customId: string;
  placeholder?: string | null | undefined;
  minValues?: number | null | undefined;
  maxValues?: number | null | undefined;
  disabled?: boolean | null | undefined;
  options: Array<SelectOption>;
};

/** @internal */
export const StringSelect$inboundSchema: z.ZodType<
  StringSelect,
  z.ZodTypeDef,
  unknown
> = z.object({
  type: z.literal(1).optional(),
  custom_id: z.string(),
  placeholder: z.nullable(z.string()).optional(),
  min_values: z.nullable(z.number().int()).optional(),
  max_values: z.nullable(z.number().int()).optional(),
  disabled: z.nullable(z.boolean()).optional(),
  options: z.array(SelectOption$inboundSchema),
}).transform((v) => {
  return remap$(v, {
    "custom_id": "customId",
    "min_values": "minValues",
    "max_values": "maxValues",
  });
});

/** @internal */
export type StringSelect$Outbound = {
  type: 1;
  custom_id: string;
  placeholder?: string | null | undefined;
  min_values?: number | null | undefined;
  max_values?: number | null | undefined;
  disabled?: boolean | null | undefined;
  options: Array<SelectOption$Outbound>;
};

/** @internal */
export const StringSelect$outboundSchema: z.ZodType<
  StringSelect$Outbound,
  z.ZodTypeDef,
  StringSelect
> = z.object({
  type: z.literal(1).default(1 as const),
  customId: z.string(),
  placeholder: z.nullable(z.string()).optional(),
  minValues: z.nullable(z.number().int()).optional(),
  maxValues: z.nullable(z.number().int()).optional(),
  disabled: z.nullable(z.boolean()).optional(),
  options: z.array(SelectOption$outboundSchema),
}).transform((v) => {
  return remap$(v, {
    customId: "custom_id",
    minValues: "min_values",
    maxValues: "max_values",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace StringSelect$ {
  /** @deprecated use `StringSelect$inboundSchema` instead. */
  export const inboundSchema = StringSelect$inboundSchema;
  /** @deprecated use `StringSelect$outboundSchema` instead. */
  export const outboundSchema = StringSelect$outboundSchema;
  /** @deprecated use `StringSelect$Outbound` instead. */
  export type Outbound = StringSelect$Outbound;
}
