/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";

export type UpdateDefaultReactionEmojiRequest = {
  emojiId?: string | null | undefined;
  emojiName?: string | null | undefined;
};

/** @internal */
export const UpdateDefaultReactionEmojiRequest$inboundSchema: z.ZodType<
  UpdateDefaultReactionEmojiRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  emoji_id: z.nullable(z.string()).optional(),
  emoji_name: z.nullable(z.string()).optional(),
}).transform((v) => {
  return remap$(v, {
    "emoji_id": "emojiId",
    "emoji_name": "emojiName",
  });
});

/** @internal */
export type UpdateDefaultReactionEmojiRequest$Outbound = {
  emoji_id?: string | null | undefined;
  emoji_name?: string | null | undefined;
};

/** @internal */
export const UpdateDefaultReactionEmojiRequest$outboundSchema: z.ZodType<
  UpdateDefaultReactionEmojiRequest$Outbound,
  z.ZodTypeDef,
  UpdateDefaultReactionEmojiRequest
> = z.object({
  emojiId: z.nullable(z.string()).optional(),
  emojiName: z.nullable(z.string()).optional(),
}).transform((v) => {
  return remap$(v, {
    emojiId: "emoji_id",
    emojiName: "emoji_name",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace UpdateDefaultReactionEmojiRequest$ {
  /** @deprecated use `UpdateDefaultReactionEmojiRequest$inboundSchema` instead. */
  export const inboundSchema = UpdateDefaultReactionEmojiRequest$inboundSchema;
  /** @deprecated use `UpdateDefaultReactionEmojiRequest$outboundSchema` instead. */
  export const outboundSchema =
    UpdateDefaultReactionEmojiRequest$outboundSchema;
  /** @deprecated use `UpdateDefaultReactionEmojiRequest$Outbound` instead. */
  export type Outbound = UpdateDefaultReactionEmojiRequest$Outbound;
}
