/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type UserAvatarDecorationResponse = {};

/** @internal */
export const UserAvatarDecorationResponse$inboundSchema: z.ZodType<
  UserAvatarDecorationResponse,
  z.ZodTypeDef,
  unknown
> = z.object({});

/** @internal */
export type UserAvatarDecorationResponse$Outbound = {};

/** @internal */
export const UserAvatarDecorationResponse$outboundSchema: z.ZodType<
  UserAvatarDecorationResponse$Outbound,
  z.ZodTypeDef,
  UserAvatarDecorationResponse
> = z.object({});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace UserAvatarDecorationResponse$ {
  /** @deprecated use `UserAvatarDecorationResponse$inboundSchema` instead. */
  export const inboundSchema = UserAvatarDecorationResponse$inboundSchema;
  /** @deprecated use `UserAvatarDecorationResponse$outboundSchema` instead. */
  export const outboundSchema = UserAvatarDecorationResponse$outboundSchema;
  /** @deprecated use `UserAvatarDecorationResponse$Outbound` instead. */
  export type Outbound = UserAvatarDecorationResponse$Outbound;
}

export function userAvatarDecorationResponseToJSON(
  userAvatarDecorationResponse: UserAvatarDecorationResponse,
): string {
  return JSON.stringify(
    UserAvatarDecorationResponse$outboundSchema.parse(
      userAvatarDecorationResponse,
    ),
  );
}

export function userAvatarDecorationResponseFromJSON(
  jsonString: string,
): SafeParseResult<UserAvatarDecorationResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => UserAvatarDecorationResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'UserAvatarDecorationResponse' from JSON`,
  );
}
